#!/bin/sh

#The compile script
name="Journal"

valac \
--pkg gtk+-3.0 \
--pkg libsoup-2.4 \
--pkg json-glib-1.0 \
--pkg gtksourceview-3.0 \
-o $name \
src/Journal.vala \
src/Notebook.vala \
src/Share.vala \
src/Tab.vala \
src/Window.vala \
src/Files.vala \
src/dynamiclist.vala